// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: s3-pro-test

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t *ui_HomeScreen;
extern void ui_event_Dropdown1( lv_event_t * e);
extern void ui_event_PaletteDropdown( lv_event_t * e);
extern lv_obj_t *ui_FilterDropdown;
extern lv_obj_t *ui_PaletteDropdown;
extern lv_obj_t *ui_Image1;
// CUSTOM VARIABLES
void ui_set_filter_mode(int mode);
void ui_set_palette_index(int idx);
void ui_get_palette(const uint32_t **palette, int *size);
void ui_set_flash_enabled(bool enabled);
bool ui_is_flash_enabled(void);
lv_obj_t *ui_get_gallery_button(void);
int ui_get_filter_mode(void);
bool ui_get_camera_rotation(void);
void ui_pause_camera_timer(void);
void ui_resume_camera_timer(void);
void ui_event_FlashSwitch(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
