// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: s3-pro-test
#include <Arduino.h>
#include "../ui.h"
#include <esp_camera.h>
#include <Preferences.h>
#include "ui.h"
#include "../../../src/utilities.h"
#include "lvgl.h"
#include "ui_SettingsScreen.h"
#include "ui_GalleryScreen.h"
#include "stdio.h"
#include "stdlib.h"
#include "../../../../include/filter.h"
#include "../../../../include/palettes.h"
#include <USB.h>
#include <USBMSC.h>
#include <FS.h>
#include <SD.h>
USBMSC msc;

#define EYE_COLOR_INACTIVE lv_color_white()
#define EYE_COLOR_ACTIVE lv_palette_main(LV_PALETTE_GREEN)

// External status functions from main.cpp
extern uint32_t ui_get_sd_free_mb();
extern uint16_t ui_get_battery_voltage();
extern bool ui_is_charging();
extern bool ui_is_usb_connected();

lv_obj_t *ui_HomeScreen = NULL;
lv_obj_t *ui_FilterDropdown = NULL;
lv_obj_t *ui_PaletteDropdown = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_fps_label = NULL;
static lv_obj_t *ui_status_sd_label = NULL;
static lv_obj_t *ui_status_batt_label = NULL;
static lv_timer_t *status_timer = NULL;

static int32_t onWrite(uint32_t lba, uint32_t offset, uint8_t *buffer, uint32_t bufsize)
{
    uint32_t secSize = SD.sectorSize();
    if (!secSize)
    {
        return false; // disk error
    }
    log_v("Write lba: %ld\toffset: %ld\tbufsize: %ld", lba, offset, bufsize);
    for (int x = 0; x < bufsize / secSize; x++)
    {
        uint8_t blkbuffer[secSize];
        memcpy(blkbuffer, (uint8_t *)buffer + secSize * x, secSize);
        if (!SD.writeRAW(blkbuffer, lba + x))
        {
            return false;
        }
    }
    return bufsize;
}

static int32_t onRead(uint32_t lba, uint32_t offset, void *buffer, uint32_t bufsize)
{
    uint32_t secSize = SD.sectorSize();
    if (!secSize)
    {
        return false; // disk error
    }
    log_v("Read lba: %ld\toffset: %ld\tbufsize: %ld\tsector: %lu", lba, offset, bufsize, secSize);
    for (int x = 0; x < bufsize / secSize; x++)
    {
        if (!SD.readRAW((uint8_t *)buffer + (x * secSize), lba + x))
        {
            return false; // outside of volume boundary
        }
    }
    return bufsize;
}

static bool onStartStop(uint8_t power_condition, bool start, bool load_eject)
{
    log_i("Start/Stop power: %u\tstart: %d\teject: %d", power_condition, start, load_eject);
    return true;
}

static void usbEventCallback(void *arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
{
    if (event_base == ARDUINO_USB_EVENTS)
    {
        arduino_usb_event_data_t *data = (arduino_usb_event_data_t *)event_data;
        switch (event_id)
        {
        case ARDUINO_USB_STARTED_EVENT:
            Serial.println("USB PLUGGED");
            break;
        case ARDUINO_USB_STOPPED_EVENT:
            Serial.println("USB UNPLUGGED");
            break;
        case ARDUINO_USB_SUSPEND_EVENT:
            Serial.printf("USB SUSPENDED: remote_wakeup_en: %u\n", data->suspend.remote_wakeup_en);
            break;
        case ARDUINO_USB_RESUME_EVENT:
            Serial.println("USB RESUMED");
            break;

        default:
            break;
        }
    }
}

static void status_timer_cb(lv_timer_t *timer)
{
    LV_UNUSED(timer);

    // Update SD card free space
    uint32_t sd_free = ui_get_sd_free_mb();
    if (sd_free > 0)
    {
        if (sd_free >= 1024)
        {
            lv_label_set_text_fmt(ui_status_sd_label, LV_SYMBOL_SD_CARD " %.1fGB", sd_free / 1024.0f);
        }
        else
        {
            lv_label_set_text_fmt(ui_status_sd_label, LV_SYMBOL_SD_CARD " %luMB", (unsigned long)sd_free);
        }
    }
    else
    {
        lv_label_set_text(ui_status_sd_label, LV_SYMBOL_SD_CARD " --");
    }

    // Update battery status
    uint16_t batt_mv = ui_get_battery_voltage();
    bool charging = ui_is_charging();
    bool usb = ui_is_usb_connected();

    // Calculate approximate percentage (3.3V = 0%, 4.2V = 100%)
    int pct = 0;
    if (batt_mv > 3300)
    {
        pct = (batt_mv - 3300) * 100 / 900;
        if (pct > 100)
            pct = 100;
        if (pct < 0)
            pct = 0;
    }

    const char *icon = LV_SYMBOL_BATTERY_FULL;
    if (charging)
    {
        icon = LV_SYMBOL_CHARGE;
    }
    else if (pct <= 10)
    {
        icon = LV_SYMBOL_BATTERY_EMPTY;
    }
    else if (pct <= 30)
    {
        icon = LV_SYMBOL_BATTERY_1;
    }
    else if (pct <= 60)
    {
        icon = LV_SYMBOL_BATTERY_2;
    }
    else if (pct <= 80)
    {
        icon = LV_SYMBOL_BATTERY_3;
    }

    if (usb && !charging)
    {
        lv_label_set_text_fmt(ui_status_batt_label, "%s %d%% " LV_SYMBOL_USB, icon, pct);
    }
    else
    {
        lv_label_set_text_fmt(ui_status_batt_label, "%s %d%%", icon, pct);
    }
}

lv_obj_t *ui_camera_canvas = NULL;
lv_timer_t *camera_timer = NULL;
bool camera_get_photo_flag = false;
bool camera_led_open_flag = true;
bool camera_rotation_flag = false;
lv_obj_t *ui_flash_switch = NULL;
lv_obj_t *ui_gallery_button = NULL;
lv_obj_t *ui_settings_button = NULL;
lv_obj_t *ui_camera_settings_button = NULL;
static lv_obj_t *ui_camera_settings_icon = NULL;

static lv_obj_t *ui_filter_column = NULL;
static lv_obj_t *ui_camera_settings_column = NULL;
static bool camera_settings_visible = false;

// Forward declarations for handlers used before definition
void ui_event_FlashSwitch(lv_event_t *e);
void ui_event_StorageSwitch(lv_event_t *e);

typedef enum
{
    CAMERA_FILTER_NONE = 0,
    CAMERA_FILTER_PIXELATE,
    CAMERA_FILTER_DITHER,
    CAMERA_FILTER_EDGE
} camera_filter_t;

static camera_filter_t current_filter = CAMERA_FILTER_NONE;
static Preferences ui_prefs;
static bool ui_prefs_ready = false;
static const char *UI_PREF_NAMESPACE = "ui_state";
static const char *UI_PREF_FILTER_KEY = "filter_mode";
static const char *UI_PREF_PALETTE_KEY = "palette_idx";
static const char *UI_PREF_FLASH_KEY = "flash_enabled";

typedef struct
{
    const uint32_t *palette;
    int size;
} palette_option_t;

static const palette_option_t kPaletteOptions[] = {
    {PALETTE_SUNSET, PALETTE_SUNSET_SIZE},
    {PALETTE_YELLOW_BROWN, PALETTE_YELLOW_BROWN_SIZE},
    {PALETTE_GRAYSCALE, PALETTE_GRAYSCALE_SIZE},
    {PALETTE_GAMEBOY, PALETTE_GAMEBOY_SIZE},
    {PALETTE_CYBERPUNK, PALETTE_CYBERPUNK_SIZE},
    {PALETTE_AUTUMN, PALETTE_AUTUMN_SIZE},
    {PALETTE_OCEAN, PALETTE_OCEAN_SIZE},
    {PALETTE_VAPORWAVE, PALETTE_VAPORWAVE_SIZE},
    {PALETTE_DESERT, PALETTE_DESERT_SIZE},
    {PALETTE_SAKURA, PALETTE_SAKURA_SIZE},
    {PALETTE_MINT, PALETTE_MINT_SIZE},
    {PALETTE_FIRE, PALETTE_FIRE_SIZE},
    {PALETTE_ARCTIC, PALETTE_ARCTIC_SIZE},
    {PALETTE_SEPIA, PALETTE_SEPIA_SIZE},
    {PALETTE_NEON, PALETTE_NEON_SIZE},
    {PALETTE_PASTEL, PALETTE_PASTEL_SIZE},
    {PALETTE_BW, PALETTE_BW_SIZE},
    {PALETTE_4COLOR, PALETTE_4COLOR_SIZE},
    {PALETTE_16COLOR, PALETTE_16COLOR_SIZE},
    {PALETTE_FRESTA, PALETTE_FRESTA_SIZE},
};
static const uint8_t kPaletteOptionCount = sizeof(kPaletteOptions) / sizeof(kPaletteOptions[0]);
static int current_palette_index = 0;

static inline int clamp_palette_index(int idx)
{
    if (idx < 0 || idx >= kPaletteOptionCount)
    {
        return 0;
    }
    return idx;
}

static const uint32_t *get_current_palette(int &out_size)
{
    current_palette_index = clamp_palette_index(current_palette_index);
    out_size = kPaletteOptions[current_palette_index].size;
    return kPaletteOptions[current_palette_index].palette;
}

static uint8_t *camera_canvas_buf = NULL;
static size_t camera_canvas_buf_size = 0;

static inline uint16_t swap_rgb565_bytes(uint16_t px)
{
    return (px >> 8) | (px << 8);
}

static bool ensure_camera_canvas_buffer(size_t bytes)
{
    if (camera_canvas_buf_size >= bytes)
    {
        return true;
    }

    uint8_t *new_buf = (uint8_t *)realloc(camera_canvas_buf, bytes);
    if (!new_buf)
    {
        return false;
    }

    camera_canvas_buf = new_buf;
    camera_canvas_buf_size = bytes;
    return true;
}

static void rotate_frame_90_clockwise(uint16_t *dst, const uint16_t *src, size_t width, size_t height)
{
    for (size_t y = 0; y < height; y++)
    {
        for (size_t x = 0; x < width; x++)
        {
            size_t src_idx = y * width + x;
            size_t dst_idx = x * height + (height - 1 - y);
            dst[dst_idx] = swap_rgb565_bytes(src[src_idx]);
        }
    }
}

static void copy_frame(uint16_t *dst, const uint16_t *src, size_t pixel_count)
{
    for (size_t i = 0; i < pixel_count; i++)
    {
        dst[i] = swap_rgb565_bytes(src[i]);
    }
}

static void px_swap(uint8_t *a, uint8_t *b)
{
    uint8_t c = *a;
    *a = *b;
    *b = c;
}

static void apply_selected_filter(camera_fb_t *frame)
{
    switch (current_filter)
    {
    case CAMERA_FILTER_PIXELATE:
        applyPixelate(frame, 8, false);
        break;
    case CAMERA_FILTER_DITHER:
    {
        int palette_size = 0;
        const uint32_t *palette = get_current_palette(palette_size);
        applyColorPalette((uint16_t *)frame->buf, frame->width, frame->height, palette, palette_size, 1, 1, 2);
    }
    break;
    case CAMERA_FILTER_EDGE:
        applyEdgeDetection(frame, 1);
        break;
    case CAMERA_FILTER_NONE:
    default:
        break;
    }
}

void ui_set_filter_mode(int mode)
{
    if (mode < CAMERA_FILTER_NONE || mode > CAMERA_FILTER_EDGE)
    {
        mode = CAMERA_FILTER_NONE;
    }
    current_filter = (camera_filter_t)mode;
    if (ui_prefs_ready)
    {
        ui_prefs.putInt(UI_PREF_FILTER_KEY, current_filter);
    }
}

int ui_get_filter_mode(void)
{
    return static_cast<int>(current_filter);
}

void ui_get_palette(const uint32_t **palette, int *size)
{
    if (!palette || !size)
    {
        return;
    }
    *size = 0;
    *palette = get_current_palette(*size);
}

void ui_set_palette_index(int idx)
{
    current_palette_index = clamp_palette_index(idx);
    if (ui_prefs_ready)
    {
        ui_prefs.putInt(UI_PREF_PALETTE_KEY, current_palette_index);
    }
}

void ui_set_flash_enabled(bool enabled)
{
    camera_led_open_flag = enabled;
    if (ui_flash_switch)
    {
        if (enabled)
        {
            lv_obj_add_state(ui_flash_switch, LV_STATE_CHECKED);
        }
        else
        {
            lv_obj_clear_state(ui_flash_switch, LV_STATE_CHECKED);
        }
    }
    if (ui_prefs_ready)
    {
        ui_prefs.putBool(UI_PREF_FLASH_KEY, enabled);
    }
}

bool ui_is_flash_enabled(void)
{
    return camera_led_open_flag;
}

bool ui_get_camera_rotation(void)
{
    return camera_rotation_flag;
}

void ui_pause_camera_timer(void)
{
    if (camera_timer)
    {
        lv_timer_pause(camera_timer);
    }
}

void ui_resume_camera_timer(void)
{
    if (camera_timer)
    {
        lv_timer_resume(camera_timer);
    }
}

static void camera_video_play(lv_timer_t *t)
{
    // lv_async_call(cmaera_async_play, NULL);
    static uint32_t last_fps_tick = 0;
    static uint16_t frame_counter = 0;

    camera_fb_t *frame = esp_camera_fb_get();
    if (frame)
    {
        sensor_t *s = esp_camera_sensor_get();
        // ESP_LOGI("", "id=%d, w=%d, h=%d, len=%d", s->id.PID, frame->width, frame->height, frame->len);

        apply_selected_filter(frame);

        if (!ensure_camera_canvas_buffer(frame->len))
        {
            esp_camera_fb_return(frame);
            return;
        }

        uint16_t *dst_pixels = (uint16_t *)camera_canvas_buf;
        const uint16_t *src_pixels = (const uint16_t *)frame->buf;
        size_t pixel_count = frame->len / 2;

        if (camera_rotation_flag)
        {
            rotate_frame_90_clockwise(dst_pixels, src_pixels, frame->width, frame->height);
            lv_canvas_set_buffer(ui_camera_canvas, camera_canvas_buf, frame->height, frame->width, LV_IMG_CF_TRUE_COLOR);
        }
        else
        {
            copy_frame(dst_pixels, src_pixels, pixel_count);
            lv_canvas_set_buffer(ui_camera_canvas, camera_canvas_buf, frame->width, frame->height, LV_IMG_CF_TRUE_COLOR);
        }

        if (camera_get_photo_flag)
        {
            camera_get_photo_flag = false;
            if (camera_led_open_flag)
            {
                // ledcWrite(LEDC_WHITE_CH, 20);
                // delay(400);
                // ledcWrite(LEDC_WHITE_CH, 0);
            }

            // if (sd_card_get_init_flag())
            // {
            //     static uint16_t img_idx = 1000;
            //     char path[32];
            //     lv_snprintf(path, 32, "%s%s%d%s", TARGET_FOLDER, "/img", img_idx++, ".bmp");
            //     // sd_card_write(path, frame->buf, frame->len);
            //     // sd_card_bmp_img(path, frame->width, frame->height, frame->buf);
            //     sd_card_bmp_lvgl(path, frame->width, frame->height, ui_camera_canvas);
            // }
            // else
            // {
            //     Serial.println("No find SD card!");
            //     prompt_info("No find SD card!", UI_PROMPT_TIME);
            // }
        }
        frame_counter++;

        uint32_t now = lv_tick_get();
        if (now - last_fps_tick >= 1000 && ui_fps_label)
        {
            uint32_t elapsed = now - last_fps_tick;
            uint32_t fps = (frame_counter * 1000) / (elapsed ? elapsed : 1);
            lv_label_set_text_fmt(ui_fps_label, "%lu FPS", static_cast<unsigned long>(fps));
            last_fps_tick = now;
            frame_counter = 0;
        }

        esp_camera_fb_return(frame);
    }
}

static void ui_event_SettingsButton(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED)
    {
        return;
    }
    ui_settings_show();
}

static void ui_event_CameraSettingsButton(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED)
        return;

    camera_settings_visible = !camera_settings_visible;

    if (camera_settings_visible)
    {
        lv_obj_add_flag(ui_filter_column, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_camera_settings_column, LV_OBJ_FLAG_HIDDEN);

        /* ✅ Eye active color */
        lv_obj_set_style_text_color(ui_camera_settings_icon,
                                    EYE_COLOR_ACTIVE, 0);
    }
    else
    {
        lv_obj_clear_flag(ui_filter_column, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_flag(ui_camera_settings_column, LV_OBJ_FLAG_HIDDEN);

        /* ✅ Eye inactive color */
        lv_obj_set_style_text_color(ui_camera_settings_icon,
                                    EYE_COLOR_INACTIVE, 0);
    }
}

static void ui_event_GalleryButton(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED)
    {
        return;
    }
    ui_gallery_show();
}

// event funtions
void ui_event_Dropdown1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        changeState(e);
    }
}

void ui_event_PaletteDropdown(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_VALUE_CHANGED)
    {
        return;
    }

    lv_obj_t *dropdown = lv_event_get_target(e);
    if (!dropdown)
    {
        return;
    }

    uint16_t selected_value = lv_dropdown_get_selected(dropdown);
    ui_set_palette_index(static_cast<int>(selected_value));
}

void ui_event_FlashSwitch(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_VALUE_CHANGED)
    {
        return;
    }

    lv_obj_t *target = lv_event_get_target(e);
    if (!target)
    {
        return;
    }

    bool enabled = lv_obj_has_state(target, LV_STATE_CHECKED);
    ui_set_flash_enabled(enabled);
}

void ui_event_StorageSwitch(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_VALUE_CHANGED)
    {
        return;
    }

    lv_obj_t *target = lv_event_get_target(e);
    if (!target)
    {
        return;
    }

    bool enabled = lv_obj_has_state(target, LV_STATE_CHECKED);

    if (enabled)
    {
        msc.vendorID("ESP32");
        msc.productID("USB_MSC");
        msc.productRevision("1.0");
        msc.onRead(onRead);
        msc.onWrite(onWrite);
        msc.onStartStop(onStartStop);
        msc.mediaPresent(true);
        msc.begin(SD.numSectors(), SD.sectorSize());
        USB.begin();
        USB.onEvent(usbEventCallback);
    }
    else
    {
        ESP.restart();
    }
}

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    if (!ui_prefs_ready)
    {
        ui_prefs_ready = ui_prefs.begin(UI_PREF_NAMESPACE, false);
        if (ui_prefs_ready)
        {
            int stored_filter = ui_prefs.getInt(UI_PREF_FILTER_KEY, current_filter);
            current_filter = (camera_filter_t)stored_filter;
            current_palette_index = clamp_palette_index(ui_prefs.getInt(UI_PREF_PALETTE_KEY, current_palette_index));
            camera_led_open_flag = ui_prefs.getBool(UI_PREF_FLASH_KEY, camera_led_open_flag);
        }
    }

    // Status bar row (SD card + battery)
    lv_obj_t *ui_status_row = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_status_row, LV_PCT(100));
    lv_obj_set_height(ui_status_row, LV_SIZE_CONTENT);
    lv_obj_clear_flag(ui_status_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_status_row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_status_row, 0, 0);
    lv_obj_set_style_pad_all(ui_status_row, 0, 0);
    lv_obj_set_style_pad_column(ui_status_row, 8, 0);
    lv_obj_set_style_pad_row(ui_status_row, 8, 0);
    lv_obj_set_flex_flow(ui_status_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_status_row, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_camera_canvas = lv_canvas_create(ui_HomeScreen);
    lv_obj_set_width(ui_camera_canvas, 222);
    lv_obj_set_height(ui_camera_canvas, 176);
    lv_obj_set_x(ui_camera_canvas, 0);
    lv_obj_set_y(ui_camera_canvas, 14);
    lv_obj_set_align(ui_camera_canvas, LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_camera_canvas, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_camera_canvas, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_fps_label = lv_label_create(ui_camera_canvas);
    lv_label_set_text(ui_fps_label, "-- FPS");
    lv_obj_set_style_bg_opa(ui_fps_label, LV_OPA_TRANSP, 0);
    lv_obj_set_style_text_color(ui_fps_label, lv_color_white(), 0);
    lv_obj_set_style_text_font(ui_fps_label, &lv_font_montserrat_12, 0);
    lv_obj_set_style_pad_all(ui_fps_label, 4, 0);
    lv_obj_set_style_radius(ui_fps_label, 4, 0);
    lv_obj_align(ui_fps_label, LV_ALIGN_BOTTOM_LEFT, 6, -4);

    camera_timer = lv_timer_create(camera_video_play, 50, NULL);
    lv_timer_ready(camera_timer);

    lv_obj_t *ui_bottom_panel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_size(ui_bottom_panel, 222, 480 - 176 - 14);
    lv_obj_set_x(ui_bottom_panel, 0);
    lv_obj_set_y(ui_bottom_panel, 176 + 14);
    lv_obj_set_align(ui_bottom_panel, LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(ui_bottom_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_bottom_panel, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_bottom_panel, 0, 0);
    lv_obj_set_style_pad_all(ui_bottom_panel, 8, 0);
    lv_obj_set_style_pad_row(ui_bottom_panel, 8, 0);
    lv_obj_set_flex_flow(ui_bottom_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_bottom_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

    ui_status_sd_label = lv_label_create(ui_status_row);
    lv_label_set_text(ui_status_sd_label, LV_SYMBOL_SD_CARD " --");
    lv_obj_set_style_text_font(ui_status_sd_label, &lv_font_montserrat_12, 0);
    lv_obj_set_style_text_color(ui_status_sd_label, lv_color_white(), 0);

    ui_status_batt_label = lv_label_create(ui_status_row);
    lv_label_set_text(ui_status_batt_label, LV_SYMBOL_BATTERY_FULL " --");
    lv_obj_set_style_text_font(ui_status_batt_label, &lv_font_montserrat_12, 0);
    lv_obj_set_style_text_color(ui_status_batt_label, lv_color_white(), 0);

    ui_filter_column = lv_obj_create(ui_bottom_panel);
    lv_obj_set_width(ui_filter_column, LV_PCT(100));
    lv_obj_set_height(ui_filter_column, LV_SIZE_CONTENT);
    lv_obj_clear_flag(ui_filter_column, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_filter_column, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_filter_column, 0, 0);

    /* Padding */
    lv_obj_set_style_pad_all(ui_filter_column, 0, 0);
    lv_obj_set_style_pad_row(ui_filter_column, 8, 0); // vertical spacing between items

    /* Flex column */
    lv_obj_set_flex_flow(ui_filter_column, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(
        ui_filter_column,
        LV_FLEX_ALIGN_START, // main axis (top)
        LV_FLEX_ALIGN_START, // cross axis (left)
        LV_FLEX_ALIGN_CENTER);

    /* Filter dropdown */
    ui_FilterDropdown = lv_dropdown_create(ui_filter_column);
    lv_obj_set_width(ui_FilterDropdown, LV_PCT(100));
    lv_obj_set_height(ui_FilterDropdown, 48);
    lv_obj_add_flag(ui_FilterDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_add_event_cb(ui_FilterDropdown, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_set_style_pad_ver(ui_FilterDropdown, 12, LV_PART_MAIN);

    lv_dropdown_set_options_static(
        ui_FilterDropdown,
        "No filter\nPixelate\nDithering\nEdge detect");
    lv_dropdown_set_selected(ui_FilterDropdown, current_filter);

    /* Palette dropdown */
    ui_PaletteDropdown = lv_dropdown_create(ui_filter_column);
    lv_obj_set_width(ui_PaletteDropdown, LV_PCT(100));
    lv_obj_set_height(ui_PaletteDropdown, 48);
    lv_obj_add_flag(ui_PaletteDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_add_event_cb(ui_PaletteDropdown, ui_event_PaletteDropdown, LV_EVENT_ALL, NULL);
    lv_obj_set_style_pad_ver(ui_PaletteDropdown, 12, LV_PART_MAIN);

    lv_dropdown_set_options_static(
        ui_PaletteDropdown,
        "Sunset\n"
        "Yellow/Brown\n"
        "Grayscale\n"
        "Game Boy\n"
        "Cyberpunk\n"
        "Autumn\n"
        "Ocean\n"
        "Vaporwave\n"
        "Desert\n"
        "Sakura\n"
        "Mint\n"
        "Fire\n"
        "Arctic\n"
        "Sepia\n"
        "Neon\n"
        "Pastel\n"
        "Black & White\n"
        "CGA 4-color\n"
        "VGA 16-color\n"
        "Fresta");
    lv_dropdown_set_selected(ui_PaletteDropdown, current_palette_index);

    /* Camera settings column (hidden by default) */
    ui_camera_settings_column = lv_obj_create(ui_bottom_panel);
    lv_obj_set_width(ui_camera_settings_column, LV_PCT(100));
    lv_obj_set_height(ui_camera_settings_column, LV_SIZE_CONTENT);
    lv_obj_clear_flag(ui_camera_settings_column, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_camera_settings_column, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_camera_settings_column, 0, 0);

    lv_obj_set_style_pad_all(ui_camera_settings_column, 0, 0);
    lv_obj_set_style_pad_row(ui_camera_settings_column, 8, 0);

    lv_obj_set_flex_flow(ui_camera_settings_column, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(
        ui_camera_settings_column,
        LV_FLEX_ALIGN_START,
        LV_FLEX_ALIGN_START,
        LV_FLEX_ALIGN_CENTER);

    /* Example camera settings */
    lv_obj_t *label = lv_label_create(ui_camera_settings_column);
    lv_label_set_text(label, "Camera settings");
    lv_obj_set_style_text_font(label, &lv_font_montserrat_14, 0);

    /* Flash switch */
    ui_flash_switch = lv_switch_create(ui_camera_settings_column);
    lv_obj_add_event_cb(ui_flash_switch, ui_event_FlashSwitch, LV_EVENT_VALUE_CHANGED, NULL);
    if (camera_led_open_flag)
    {
        lv_obj_add_state(ui_flash_switch, LV_STATE_CHECKED);
    }

    /* Hide initially */
    lv_obj_add_flag(ui_camera_settings_column, LV_OBJ_FLAG_HIDDEN);

    // Spacer to push navigation buttons to the bottom of the right panel
    lv_obj_t *ui_nav_spacer = lv_obj_create(ui_bottom_panel);
    lv_obj_clear_flag(ui_nav_spacer, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_nav_spacer, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_nav_spacer, 0, 0);
    lv_obj_set_width(ui_nav_spacer, LV_PCT(100));
    lv_obj_set_height(ui_nav_spacer, 0);
    lv_obj_set_flex_grow(ui_nav_spacer, 1);

    lv_obj_t *ui_nav_row = lv_obj_create(ui_bottom_panel);
    lv_obj_set_width(ui_nav_row, LV_PCT(100));
    lv_obj_set_height(ui_nav_row, LV_SIZE_CONTENT);
    lv_obj_clear_flag(ui_nav_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_nav_row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_nav_row, 0, 0);
    lv_obj_set_style_pad_all(ui_nav_row, 0, 0);
    lv_obj_set_style_pad_column(ui_nav_row, 12, 0);
    lv_obj_set_flex_flow(ui_nav_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_nav_row, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    // Left: Gallery
    ui_gallery_button = lv_btn_create(ui_nav_row);
    lv_obj_set_size(ui_gallery_button, 64, 64);
    lv_obj_set_style_bg_color(ui_gallery_button, lv_palette_main(LV_PALETTE_BLUE), 0);
    lv_obj_set_style_bg_opa(ui_gallery_button, LV_OPA_80, 0);
    lv_obj_set_style_radius(ui_gallery_button, 8, 0);
    lv_obj_set_style_text_color(ui_gallery_button, lv_color_white(), 0);
    lv_obj_t *gallery_label = lv_label_create(ui_gallery_button);
    lv_label_set_text(gallery_label, LV_SYMBOL_IMAGE);
    lv_obj_center(gallery_label);
    lv_obj_set_style_text_font(gallery_label, &lv_font_montserrat_28, 0);
    lv_obj_add_event_cb(ui_gallery_button, ui_event_GalleryButton, LV_EVENT_CLICKED, NULL);

    // Center: Camera settings
    ui_camera_settings_button = lv_btn_create(ui_nav_row);
    lv_obj_set_size(ui_camera_settings_button, 64, 64);
    lv_obj_set_style_bg_color(ui_camera_settings_button, lv_palette_main(LV_PALETTE_BROWN), 0);
    lv_obj_set_style_bg_opa(ui_camera_settings_button, LV_OPA_80, 0);
    lv_obj_set_style_radius(ui_camera_settings_button, 8, 0);
    lv_obj_set_style_text_color(ui_camera_settings_button, lv_color_white(), 0);
    lv_obj_add_event_cb(ui_camera_settings_button, ui_event_CameraSettingsButton, LV_EVENT_CLICKED, NULL);

    ui_camera_settings_icon = lv_label_create(ui_camera_settings_button);
    lv_label_set_text(ui_camera_settings_icon, LV_SYMBOL_EYE_OPEN);
    lv_obj_set_style_text_font(ui_camera_settings_icon,
                               &lv_font_montserrat_28, 0);
    lv_obj_center(ui_camera_settings_icon);

    // Right: Settings
    ui_settings_button = lv_btn_create(ui_nav_row);
    lv_obj_set_size(ui_settings_button, 64, 64);
    lv_obj_set_style_bg_color(ui_settings_button, lv_palette_main(LV_PALETTE_GREY), 0);
    lv_obj_set_style_bg_opa(ui_settings_button, LV_OPA_80, 0);
    lv_obj_set_style_radius(ui_settings_button, 8, 0);
    lv_obj_set_style_text_color(ui_settings_button, lv_color_white(), 0);
    lv_obj_t *settings_label = lv_label_create(ui_settings_button);
    lv_label_set_text(settings_label, LV_SYMBOL_SETTINGS);
    lv_obj_set_style_text_font(settings_label, &lv_font_montserrat_28, 0);

    lv_obj_center(settings_label);
    lv_obj_add_event_cb(ui_settings_button, ui_event_SettingsButton, LV_EVENT_CLICKED, NULL);

    // Status bar update timer (every 2 seconds)
    status_timer = lv_timer_create(status_timer_cb, 2000, NULL);
    lv_timer_ready(status_timer);
}

void ui_HomeScreen_screen_destroy(void)
{
    if (status_timer)
    {
        lv_timer_del(status_timer);
        status_timer = NULL;
    }
    if (ui_HomeScreen)
        lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_FilterDropdown = NULL;
    ui_Image1 = NULL;
    ui_status_sd_label = NULL;
    ui_status_batt_label = NULL;
}

lv_obj_t *ui_get_gallery_button(void)
{
    return ui_gallery_button;
}
