// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: s3-pro-test

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Dropdown1 = NULL;lv_obj_t *ui_Image1 = NULL;
// event funtions
void ui_event_Dropdown1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      changeState( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Dropdown1 = lv_dropdown_create(ui_Screen1);
lv_obj_set_width( ui_Dropdown1, 150);
lv_obj_set_height( ui_Dropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown1, 151 );
lv_obj_set_y( ui_Dropdown1, -81 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_Image1, 296);
lv_obj_set_height( ui_Image1, 222);
lv_obj_set_x( ui_Image1, -92 );
lv_obj_set_y( ui_Image1, 0 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Dropdown1= NULL;
ui_Image1= NULL;

}
