// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: s3-pro-test
#include <Arduino.h>
#include "../ui.h"
#include <esp_camera.h>
#include "ui.h"
#include "../../../src/utilities.h"
#include "lvgl.h"
#include "stdio.h"
#include "stdlib.h"
#include "../../../../include/filter.h"
#include "../../../../include/palettes.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Dropdown1 = NULL;
lv_obj_t *ui_Image1 = NULL;
lv_obj_t *ui_fps_label = NULL;

lv_obj_t *ui_camera_canvas = NULL;
lv_timer_t *camera_timer = NULL;
bool camera_get_photo_flag = false;
bool camera_led_open_flag = true;
bool camera_rotation_flag = true;
lv_obj_t *ui_flash_switch = NULL;
lv_obj_t *ui_gallery_button = NULL;

typedef enum
{
    CAMERA_FILTER_NONE = 0,
    CAMERA_FILTER_PIXELATE,
    CAMERA_FILTER_DITHER,
    CAMERA_FILTER_EDGE
} camera_filter_t;

static camera_filter_t current_filter = CAMERA_FILTER_NONE;

static uint8_t *camera_canvas_buf = NULL;
static size_t camera_canvas_buf_size = 0;

static inline uint16_t swap_rgb565_bytes(uint16_t px)
{
    return (px >> 8) | (px << 8);
}

static bool ensure_camera_canvas_buffer(size_t bytes)
{
    if (camera_canvas_buf_size >= bytes)
    {
        return true;
    }

    uint8_t *new_buf = (uint8_t *)realloc(camera_canvas_buf, bytes);
    if (!new_buf)
    {
        return false;
    }

    camera_canvas_buf = new_buf;
    camera_canvas_buf_size = bytes;
    return true;
}

static void rotate_frame_90_clockwise(uint16_t *dst, const uint16_t *src, size_t width, size_t height)
{
    for (size_t y = 0; y < height; y++)
    {
        for (size_t x = 0; x < width; x++)
        {
            size_t src_idx = y * width + x;
            size_t dst_idx = x * height + (height - 1 - y);
            dst[dst_idx] = swap_rgb565_bytes(src[src_idx]);
        }
    }
}

static void copy_frame(uint16_t *dst, const uint16_t *src, size_t pixel_count)
{
    for (size_t i = 0; i < pixel_count; i++)
    {
        dst[i] = swap_rgb565_bytes(src[i]);
    }
}

static void px_swap(uint8_t *a, uint8_t *b)
{
    uint8_t c = *a;
    *a = *b;
    *b = c;
}

static void apply_selected_filter(camera_fb_t *frame)
{
    switch (current_filter)
    {
    case CAMERA_FILTER_PIXELATE:
        applyPixelate(frame, 8, false);
        break;
    case CAMERA_FILTER_DITHER:
        applyColorPalette( (uint16_t *)frame->buf, frame->width, frame->height, PALETTE_CYBERPUNK, PALETTE_CYBERPUNK_SIZE, 1, 2, 2);
        break;
    case CAMERA_FILTER_EDGE:
        applyEdgeDetection(frame, 1);
        break;
    case CAMERA_FILTER_NONE:
    default:
        break;
    }
}

void ui_set_filter_mode(int mode)
{
    if (mode < CAMERA_FILTER_NONE || mode > CAMERA_FILTER_EDGE)
    {
        mode = CAMERA_FILTER_NONE;
    }
    current_filter = (camera_filter_t)mode;
}

int ui_get_filter_mode(void)
{
    return static_cast<int>(current_filter);
}

void ui_set_flash_enabled(bool enabled)
{
    camera_led_open_flag = enabled;
    if (ui_flash_switch)
    {
        if (enabled)
        {
            lv_obj_add_state(ui_flash_switch, LV_STATE_CHECKED);
        }
        else
        {
            lv_obj_clear_state(ui_flash_switch, LV_STATE_CHECKED);
        }
    }
}

bool ui_is_flash_enabled(void)
{
    return camera_led_open_flag;
}

bool ui_get_camera_rotation(void)
{
    return camera_rotation_flag;
}

static void camera_video_play(lv_timer_t *t)
{
    // lv_async_call(cmaera_async_play, NULL);
    static uint32_t last_fps_tick = 0;
    static uint16_t frame_counter = 0;

    camera_fb_t *frame = esp_camera_fb_get();
    if (frame)
    {
        sensor_t *s = esp_camera_sensor_get();
        // ESP_LOGI("", "id=%d, w=%d, h=%d, len=%d", s->id.PID, frame->width, frame->height, frame->len);

        apply_selected_filter(frame);

        if (!ensure_camera_canvas_buffer(frame->len))
        {
            esp_camera_fb_return(frame);
            return;
        }

        uint16_t *dst_pixels = (uint16_t *)camera_canvas_buf;
        const uint16_t *src_pixels = (const uint16_t *)frame->buf;
        size_t pixel_count = frame->len / 2;

        if (camera_rotation_flag)
        {
            rotate_frame_90_clockwise(dst_pixels, src_pixels, frame->width, frame->height);
            lv_canvas_set_buffer(ui_camera_canvas, camera_canvas_buf, frame->height, frame->width, LV_IMG_CF_TRUE_COLOR);
        }
        else
        {
            copy_frame(dst_pixels, src_pixels, pixel_count);
            lv_canvas_set_buffer(ui_camera_canvas, camera_canvas_buf, frame->width, frame->height, LV_IMG_CF_TRUE_COLOR);
        }

        if (camera_get_photo_flag)
        {
            camera_get_photo_flag = false;
            if (camera_led_open_flag)
            {
                // ledcWrite(LEDC_WHITE_CH, 20);
                // delay(400);
                // ledcWrite(LEDC_WHITE_CH, 0);
            }

            // if (sd_card_get_init_flag())
            // {
            //     static uint16_t img_idx = 1000;
            //     char path[32];
            //     lv_snprintf(path, 32, "%s%s%d%s", TARGET_FOLDER, "/img", img_idx++, ".bmp");
            //     // sd_card_write(path, frame->buf, frame->len);
            //     // sd_card_bmp_img(path, frame->width, frame->height, frame->buf);
            //     sd_card_bmp_lvgl(path, frame->width, frame->height, ui_camera_canvas);
            // }
            // else
            // {
            //     Serial.println("No find SD card!");
            //     prompt_info("No find SD card!", UI_PROMPT_TIME);
            // }
        }
        frame_counter++;

        uint32_t now = lv_tick_get();
        if (now - last_fps_tick >= 1000 && ui_fps_label)
        {
            uint32_t elapsed = now - last_fps_tick;
            uint32_t fps = (frame_counter * 1000) / (elapsed ? elapsed : 1);
            lv_label_set_text_fmt(ui_fps_label, "%lu FPS", static_cast<unsigned long>(fps));
            last_fps_tick = now;
            frame_counter = 0;
        }

        esp_camera_fb_return(frame);
    }
}

// event funtions
void ui_event_Dropdown1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        changeState(e);
    }
}

void ui_event_FlashSwitch(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_VALUE_CHANGED)
    {
        return;
    }

    lv_obj_t *target = lv_event_get_target(e);
    if (!target)
    {
        return;
    }

    bool enabled = lv_obj_has_state(target, LV_STATE_CHECKED);
    ui_set_flash_enabled(enabled);
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_t *ui_right_panel = lv_obj_create(ui_Screen1);
    lv_obj_set_size(ui_right_panel, 240, 222);
    lv_obj_set_x(ui_right_panel, 240);
    lv_obj_set_y(ui_right_panel, 0);
    lv_obj_set_align(ui_right_panel, LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(ui_right_panel, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_right_panel, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_right_panel, 0, 0);
    lv_obj_set_style_pad_all(ui_right_panel, 12, 0);
    lv_obj_set_style_pad_row(ui_right_panel, 12, 0);
    lv_obj_set_flex_flow(ui_right_panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_right_panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

    ui_Dropdown1 = lv_dropdown_create(ui_right_panel);
    lv_obj_set_width(ui_Dropdown1, LV_PCT(100));
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT); /// 1
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_dropdown_set_options_static(ui_Dropdown1, "No filter\nPixelate\nDithering\nEdge detect");
    lv_dropdown_set_selected(ui_Dropdown1, current_filter);

    lv_obj_t *ui_flash_row = lv_obj_create(ui_right_panel);
    lv_obj_set_width(ui_flash_row, LV_PCT(100));
    lv_obj_set_height(ui_flash_row, LV_SIZE_CONTENT);
    lv_obj_clear_flag(ui_flash_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_flash_row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(ui_flash_row, 0, 0);
    lv_obj_set_style_pad_all(ui_flash_row, 0, 0);
    lv_obj_set_style_pad_row(ui_flash_row, 8, 0);
    lv_obj_set_style_pad_column(ui_flash_row, 8, 0);
    lv_obj_set_flex_flow(ui_flash_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_flash_row, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    lv_obj_t *flash_label = lv_label_create(ui_flash_row);
    lv_label_set_text(flash_label, "Flash");

    ui_flash_switch = lv_switch_create(ui_flash_row);
    if (camera_led_open_flag)
    {
        lv_obj_add_state(ui_flash_switch, LV_STATE_CHECKED);
    }
    lv_obj_add_event_cb(ui_flash_switch, ui_event_FlashSwitch, LV_EVENT_ALL, NULL);

    ui_gallery_button = lv_btn_create(ui_right_panel);
    lv_obj_set_width(ui_gallery_button, LV_PCT(100));
    lv_obj_set_height(ui_gallery_button, 40);
    lv_obj_set_style_bg_color(ui_gallery_button, lv_palette_main(LV_PALETTE_BLUE), 0);
    lv_obj_set_style_bg_opa(ui_gallery_button, LV_OPA_80, 0);
    lv_obj_set_style_radius(ui_gallery_button, 8, 0);
    lv_obj_set_style_text_color(ui_gallery_button, lv_color_white(), 0);
    lv_obj_t *gallery_label = lv_label_create(ui_gallery_button);
    lv_label_set_text(gallery_label, "Gallery");
    lv_obj_center(gallery_label);

    ui_camera_canvas = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_camera_canvas, 296);
    lv_obj_set_height(ui_camera_canvas, 222);
    lv_obj_set_x(ui_camera_canvas, -92);
    lv_obj_set_y(ui_camera_canvas, 0);
    lv_obj_set_align(ui_camera_canvas, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_camera_canvas, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_camera_canvas, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // ui_camera_canvas = lv_canvas_create(ui_Screen1);
    // lv_obj_align(ui_camera_canvas, LV_ALIGN_CENTER, 0, -80);

    ui_fps_label = lv_label_create(ui_Screen1);
    lv_label_set_text(ui_fps_label, "-- FPS");
    lv_obj_set_style_bg_opa(ui_fps_label, LV_OPA_60, 0);
    lv_obj_set_style_bg_color(ui_fps_label, lv_color_black(), 0);
    lv_obj_set_style_text_color(ui_fps_label, lv_color_white(), 0);
    lv_obj_set_style_pad_all(ui_fps_label, 4, 0);
    lv_obj_set_style_radius(ui_fps_label, 4, 0);
    lv_obj_align(ui_fps_label, LV_ALIGN_BOTTOM_RIGHT, -6, -4);

    camera_timer = lv_timer_create(camera_video_play, 50, NULL);
    lv_timer_ready(camera_timer);
    lv_timer_pause(camera_timer);
    lv_timer_resume(camera_timer);
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1)
        lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Dropdown1 = NULL;
    ui_Image1 = NULL;
}

lv_obj_t *ui_get_gallery_button(void)
{
    return ui_gallery_button;
}
