// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: s3-pro-test

#include <Arduino.h>

#include "ui.h"

void changeState(lv_event_t *e)
{
	if (!e)
	{
		return;
	}

	lv_event_code_t code = lv_event_get_code(e);
	if (code != LV_EVENT_VALUE_CHANGED)
	{
		return;
	}

	lv_obj_t *dropdown = lv_event_get_target(e);
	if (!dropdown)
	{
		return;
	}

	uint16_t selected_value = lv_dropdown_get_selected(dropdown);
	ui_set_filter_mode(static_cast<int>(selected_value));
}

