// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: s3-pro-test

#include <Arduino.h>

#include "ui.h"

void changeState(lv_event_t *e)
{
	// Cast the param to the appropriate type
	int selected_value = *(int *)e->param;

	// Print the selected value
	Serial.print("Selected value: ");
	Serial.println(selected_value);
}

